<a href="https://colab.research.google.com/github/GaurangRawat/NLP/blob/main/Word_Embedding_using_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Word Embedding Techniques  using Embedding Layer in Keras
---

In [103]:
### Libraries Used Tensorflow >2.0 and keras

In [104]:
!pip install tensorflow

In [105]:
## tensorflow
from tensorflow.keras.preprocessing.text import one_hot

In [106]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [107]:
### Vocabulary Size
voc_size=10000

##One Hot Representation
---

In [108]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[9634, 549, 60, 4464], [9634, 549, 60, 8224], [9634, 1493, 60, 6916], [2813, 3252, 3910, 2079, 4761], [2813, 3252, 3910, 2079, 6853], [4085, 9634, 9904, 60, 7233], [4853, 1558, 3460, 2079]]


##Word Embedding Representation
---

In [109]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [110]:
import numpy as np

In [111]:
### pre-padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9634  549   60 4464]
 [   0    0    0    0 9634  549   60 8224]
 [   0    0    0    0 9634 1493   60 6916]
 [   0    0    0 2813 3252 3910 2079 4761]
 [   0    0    0 2813 3252 3910 2079 6853]
 [   0    0    0 4085 9634 9904   60 7233]
 [   0    0    0    0 4853 1558 3460 2079]]


In [112]:
dim=10

In [113]:

model=Sequential()
model.add(Embedding(voc_size,10))
model.build(input_shape=(None, sent_length))  # Specify the input shape explicitly in the newer version
model.compile(optimizer='adam',loss='mse')

In [114]:
model.summary()

Model: "sequential_29"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_22 (Embedding)             │ (None, 8, 10)               │         100,000 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [120]:
embedded_docs[0]

array([   0,    0,    0,    0, 9634,  549,   60, 4464], dtype=int32)

In [119]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step


array([[[ 2.39670277e-03, -1.78712606e-02,  2.98609622e-02,
         -3.50682028e-02,  3.49080563e-03,  4.11088131e-02,
          4.51082923e-02,  2.73571275e-02, -9.56100225e-03,
         -6.90668821e-03],
        [ 2.39670277e-03, -1.78712606e-02,  2.98609622e-02,
         -3.50682028e-02,  3.49080563e-03,  4.11088131e-02,
          4.51082923e-02,  2.73571275e-02, -9.56100225e-03,
         -6.90668821e-03],
        [ 2.39670277e-03, -1.78712606e-02,  2.98609622e-02,
         -3.50682028e-02,  3.49080563e-03,  4.11088131e-02,
          4.51082923e-02,  2.73571275e-02, -9.56100225e-03,
         -6.90668821e-03],
        [ 2.39670277e-03, -1.78712606e-02,  2.98609622e-02,
         -3.50682028e-02,  3.49080563e-03,  4.11088131e-02,
          4.51082923e-02,  2.73571275e-02, -9.56100225e-03,
         -6.90668821e-03],
        [ 3.23129818e-03,  3.38447951e-02,  1.08611584e-03,
          3.82810496e-02,  4.51842658e-02,  2.65643746e-03,
          2.99709104e-02, -4.69906442e-02, -2.263648

In [123]:
input_sequence = np.expand_dims(embedded_docs[0], axis=0)  # Add batch dimension

# Predict
prediction = model.predict(input_sequence)
print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
[[[ 0.0023967  -0.01787126  0.02986096 -0.0350682   0.00349081
    0.04110881  0.04510829  0.02735713 -0.009561   -0.00690669]
  [ 0.0023967  -0.01787126  0.02986096 -0.0350682   0.00349081
    0.04110881  0.04510829  0.02735713 -0.009561   -0.00690669]
  [ 0.0023967  -0.01787126  0.02986096 -0.0350682   0.00349081
    0.04110881  0.04510829  0.02735713 -0.009561   -0.00690669]
  [ 0.0023967  -0.01787126  0.02986096 -0.0350682   0.00349081
    0.04110881  0.04510829  0.02735713 -0.009561   -0.00690669]
  [ 0.0032313   0.0338448   0.00108612  0.03828105  0.04518427
    0.00265644  0.02997091 -0.04699064 -0.02263649  0.01647547]
  [-0.01025838  0.0353459  -0.00488307 -0.00614728  0.03416753
   -0.01332136  0.01312688  0.03171927 -0.03467851 -0.00201074]
  [-0.03560395  0.01333996  0.01447518  0.04337137  0.0155325
   -0.01860553 -0.02002813  0.03268037 -0.04540955 -0.00946263]
  [-0.03061732  0.03765726  0.04914268 -0.01659971  0.025367
   -0.0368291

#Revision Assignment
---

In [124]:
### Assignment

sent_1=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [127]:
sent_1

['The world is a better place',
 'Marvel series is my favourite movie',
 'I like DC movies',
 'the cat is eating the food',
 'Tom and Jerry is my favourite movie',
 'Python is my favourite programming language']

In [134]:
voc_size=500

In [139]:
onehot1_repr=[one_hot(words,voc_size)for words in sent_1]
print(onehot1_repr)

[[51, 213, 432, 201, 465, 372], [20, 71, 432, 92, 371, 413], [217, 295, 254, 464], [51, 352, 432, 181, 51, 234], [225, 498, 180, 432, 92, 371, 413], [259, 432, 92, 371, 4, 386]]


##Word Embedding
---

In [143]:
# post padding
sent_length=8
embedded_docs1=pad_sequences(onehot1_repr,padding='post',maxlen=sent_length)
print(embedded_docs1)

[[ 51 213 432 201 465 372   0   0]
 [ 20  71 432  92 371 413   0   0]
 [217 295 254 464   0   0   0   0]
 [ 51 352 432 181  51 234   0   0]
 [225 498 180 432  92 371 413   0]
 [259 432  92 371   4 386   0   0]]


In [144]:
dim=10

In [145]:
model=Sequential()
model.add(Embedding(voc_size,10))
model.build(input_shape=(None,sent_length))
model.compile(optimizer='adam',loss='mse')

In [146]:
model.summary()

Model: "sequential_32"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_24 (Embedding)             │ (None, 8, 10)               │           5,000 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [148]:
embedded_docs1[0]

array([ 51, 213, 432, 201, 465, 372,   0,   0], dtype=int32)

In [152]:
model.predict(embedded_docs1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step


array([[[-0.04172225, -0.0205543 ,  0.04257796,  0.04810028,
          0.01017922, -0.01616739, -0.00425187, -0.03732263,
         -0.00375845,  0.04254698],
        [ 0.04040085,  0.01200991, -0.04915208, -0.00124204,
         -0.0382622 ,  0.02155453,  0.03414068, -0.00406674,
         -0.02567376,  0.00706074],
        [-0.01213423, -0.04508815, -0.04483719, -0.02832724,
         -0.02051358,  0.02696813, -0.04899561, -0.04123185,
          0.02199835, -0.04602554],
        [-0.0164338 ,  0.01386576,  0.02606258, -0.02557412,
         -0.01170758,  0.04406   , -0.04017761,  0.04136043,
         -0.00600515,  0.0027067 ],
        [-0.00767767, -0.03420886, -0.00054898,  0.03942635,
         -0.00037362,  0.00400808,  0.04770663,  0.01611731,
         -0.01116876,  0.0111353 ],
        [-0.01056918,  0.03645506,  0.04005608, -0.01994335,
          0.04533647,  0.03869518,  0.04756835, -0.01950547,
         -0.03265089, -0.03552229],
        [ 0.04136598, -0.02808245, -0.00471274, -0.0

In [151]:
input_sequence1 = np.expand_dims(embedded_docs1[0], axis=0)  # Add batch dimension

# Predict
prediction1 = model.predict(input_sequence1)
print(prediction1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
[[[-0.04172225 -0.0205543   0.04257796  0.04810028  0.01017922
   -0.01616739 -0.00425187 -0.03732263 -0.00375845  0.04254698]
  [ 0.04040085  0.01200991 -0.04915208 -0.00124204 -0.0382622
    0.02155453  0.03414068 -0.00406674 -0.02567376  0.00706074]
  [-0.01213423 -0.04508815 -0.04483719 -0.02832724 -0.02051358
    0.02696813 -0.04899561 -0.04123185  0.02199835 -0.04602554]
  [-0.0164338   0.01386576  0.02606258 -0.02557412 -0.01170758
    0.04406    -0.04017761  0.04136043 -0.00600515  0.0027067 ]
  [-0.00767767 -0.03420886 -0.00054898  0.03942635 -0.00037362
    0.00400808  0.04770663  0.01611731 -0.01116876  0.0111353 ]
  [-0.01056918  0.03645506  0.04005608 -0.01994335  0.04533647
    0.03869518  0.04756835 -0.01950547 -0.03265089 -0.03552229]
  [ 0.04136598 -0.02808245 -0.00471274 -0.03421899  0.02300601
    0.01185795  0.01658079  0.00524603 -0.02805116 -0.01510417]
  [ 0.04136598 -0.02808245 -0.00471274 -0.03421899  0.02300601
    0.01185